-- MySQL Script generated by MySQL Workbench
-- 11/25/14 18:15:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ControlCA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ControlCA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ControlCA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ControlCA` ;

-- -----------------------------------------------------
-- Table `ControlCA`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControlCA`.`Departamentos` (
  `IdDept` INT NOT NULL AUTO_INCREMENT,
  `NombreDept` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdDept`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControlCA`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControlCA`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(10) NOT NULL,
  `Password` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `EsJefe` TINYINT(1) NOT NULL DEFAULT 0,
  `IdDept` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `IdDept`),
  INDEX `fk_Usuarios_Departamentos1_idx` (`IdDept` ASC),
  CONSTRAINT `fk_Usuarios_Departamentos1`
    FOREIGN KEY (`IdDept`)
    REFERENCES `ControlCA`.`Departamentos` (`IdDept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ControlCA`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ControlCA`.`Asistencia` (
  `idAsistencia` INT NOT NULL AUTO_INCREMENT,
  `idUsuarios` INT NOT NULL,
  `EnSal` ENUM('E','S') NOT NULL,
  `Time` TIME NULL,
  PRIMARY KEY (`idAsistencia`, `idUsuarios`),
  CONSTRAINT `fk_Asistencia_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `ControlCA`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
